# interval, response_time_threshold, certificate_expired_before: can be s(second)/m(minutes)/h(hour)/d(day)

monitor:
  - url: "http://example.com"
    enabled: true
    interval: 5m
    response_time_threshold: 5s
    certificate_monitoring: true
    certificate_expired_before: 31d
